### PR TITLE
Week 2 - Server side changes. http://jtan-sps-summer20.appspot.com/

### PR DESCRIPTION
**Pull request by lolfuljames**
This commit modifies the names of link page-views -> views.
This commit also modifies the message hello world -> hello james

### CODE REVIEW

**Review by henryken — APPROVED** [review]
LGTM

**Comment by lolfuljames** [comment]
http://jtan-sps-summer20.appspot.com/ > press contact > 'hello james' appears

**Comment by henryken** [comment]
It would be good not to reuse the same PR once it gets approved.

**Review by henryken — APPROVED** [review]
LGTM

**Pull request merged**
